"""ScriptExporter: generates a standalone, reproducible Python script that
applies an approved CleaningStrategy's exact steps, with NO dependency on
this project's own package (Phase 1, FR-12: "export a reproducible cleaning
script" that can be "re-run outside the app").

Design decision: rather than generating a script that `import autoclean`
and calls `StrategyExecutor`, this module transcribes each CleaningStep
into literal, inline pandas code -- because a script that depends on this
project's package is not "standalone" in any meaningful sense; the whole
point of FR-12 is that someone without AutoClean AI+ installed can still
reproduce exactly what happened to their data.

Correctness guarantee: `tests/unit/infrastructure/test_script_exporter.py`
actually EXECUTES the generated script in a subprocess and asserts its
output is IDENTICAL to `StrategyExecutor.apply()`'s in-process result --
not just that the script "looks right."
"""

from __future__ import annotations

import logging
from pathlib import Path

from autoclean.domain.entities.cleaning_strategy import CleaningOperation, CleaningStep, CleaningStrategy

logger = logging.getLogger(__name__)

_SCRIPT_HEADER = '''#!/usr/bin/env python
"""Reproducible data-cleaning script, auto-generated by AutoClean AI+.

Strategy: {strategy_name}
{strategy_description}

This script has NO dependency on AutoClean AI+ itself -- only pandas and
numpy, which you must have installed separately (`pip install pandas numpy`).

Usage:
    python {script_filename} <input.csv> <output.csv>
"""

from __future__ import annotations

import sys

import numpy as np
import pandas as pd


def clean(df: pd.DataFrame) -> pd.DataFrame:
    """Applies the exact steps approved for this experiment, in order."""
    df = df.copy()
'''

_SCRIPT_FOOTER = '''    return df


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.csv> <output.csv>", file=sys.stderr)
        return 1
    df = pd.read_csv(sys.argv[1])
    cleaned = clean(df)
    cleaned.to_csv(sys.argv[2], index=False)
    print(f"Wrote {len(cleaned)} rows (from {len(df)} original) to {sys.argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''


class ScriptExporter:
    """Transcribes a CleaningStrategy into a standalone .py script."""

    def export(self, strategy: CleaningStrategy, output_path: str) -> str:
        script_filename = Path(output_path).name
        body_lines = [self._step_to_code(step) for step in strategy.steps]
        script_text = (
            _SCRIPT_HEADER.format(
                strategy_name=strategy.name,
                strategy_description=strategy.description or "(no description provided)",
                script_filename=script_filename,
            )
            + "\n".join(line for block in body_lines for line in block)
            + "\n"
            + _SCRIPT_FOOTER
        )

        path = Path(output_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(script_text, encoding="utf-8")
        logger.info(
            "ScriptExporter wrote reproducible script",
            extra={"strategy_id": strategy.strategy_id, "output_path": str(path)},
        )
        return str(path)

    @staticmethod
    def _step_to_code(step: CleaningStep) -> list[str]:
        operation = step.operation
        column = step.target_column

        if operation == CleaningOperation.NO_OP:
            return ["    pass  # no-op step"]

        if operation == CleaningOperation.TYPE_COERCION:
            return [f"    df[{column!r}] = pd.to_numeric(df[{column!r}], errors='coerce')"]

        if operation == CleaningOperation.EXACT_DEDUPLICATION:
            return ["    df = df.drop_duplicates(keep='first')"]

        if operation == CleaningOperation.DROP_ROWS_WITH_MISSING:
            return [f"    df = df.dropna(subset=[{column!r}])"]

        if operation == CleaningOperation.MEAN_IMPUTATION:
            return [f"    df[{column!r}] = df[{column!r}].fillna(df[{column!r}].mean())"]

        if operation == CleaningOperation.MEDIAN_IMPUTATION:
            return [f"    df[{column!r}] = df[{column!r}].fillna(df[{column!r}].median())"]

        if operation == CleaningOperation.MODE_IMPUTATION:
            return [
                f"    _mode = df[{column!r}].mode(dropna=True)",
                f"    df[{column!r}] = df[{column!r}].fillna(_mode.iloc[0] if not _mode.empty else df[{column!r}])",
            ]

        if operation == CleaningOperation.CONSTANT_IMPUTATION:
            fill_value = step.parameters.get("fill_value", 0)
            return [f"    df[{column!r}] = df[{column!r}].fillna({fill_value!r})"]

        if operation == CleaningOperation.IQR_OUTLIER_CLIPPING:
            multiplier = step.parameters.get("iqr_multiplier", 1.5)
            return [
                f"    _q1, _q3 = df[{column!r}].quantile(0.25), df[{column!r}].quantile(0.75)",
                "    _iqr = _q3 - _q1",
                "    if _iqr != 0:",
                f"        df[{column!r}] = df[{column!r}].clip(lower=_q1 - {multiplier} * _iqr, upper=_q3 + {multiplier} * _iqr)",
            ]

        if operation == CleaningOperation.IQR_OUTLIER_REMOVAL:
            multiplier = step.parameters.get("iqr_multiplier", 1.5)
            return [
                f"    _q1, _q3 = df[{column!r}].quantile(0.25), df[{column!r}].quantile(0.75)",
                "    _iqr = _q3 - _q1",
                "    if _iqr != 0:",
                f"        _lower, _upper = _q1 - {multiplier} * _iqr, _q3 + {multiplier} * _iqr",
                f"        df = df[df[{column!r}].between(_lower, _upper) | df[{column!r}].isna()]",
            ]

        raise ValueError(f"ScriptExporter: unhandled operation {operation!r}")
