"""Domain entities modeling a candidate data-cleaning strategy.

Design note (Strategy pattern, Phase 2 Section 12): `CleaningStrategy` is the
interchangeable "algorithm object" evaluated and ranked by the Evaluation
Agent (Phase 6) and, once approved, executed by the Decision & Reporting
Agent (Phase 8). This is the direct analogue of the paper's own "method"
abstraction (s1..s4) 🟦[PAPER], generalized from "one method per sub-task" to
"one ordered sequence of steps per whole-dataset strategy" 🟩[ORIGINAL].
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class CleaningOperation(str, Enum):
    """Atomic, deterministic cleaning operations a CleaningStep may perform.

    Every operation here is implemented in Python (Pandas/NumPy/Scikit-learn)
    with no LLM involvement whatsoever, per NFR-1.
    """

    # Missing values
    DROP_ROWS_WITH_MISSING = "drop_rows_with_missing"
    MEAN_IMPUTATION = "mean_imputation"
    MEDIAN_IMPUTATION = "median_imputation"
    MODE_IMPUTATION = "mode_imputation"
    CONSTANT_IMPUTATION = "constant_imputation"

    # Duplicates
    EXACT_DEDUPLICATION = "exact_deduplication"

    # Outliers
    IQR_OUTLIER_REMOVAL = "iqr_outlier_removal"
    IQR_OUTLIER_CLIPPING = "iqr_outlier_clipping"

    # Data type inconsistency
    TYPE_COERCION = "type_coercion"

    # No-op, used to construct the baseline "do nothing" strategy
    NO_OP = "no_op"


@dataclass(frozen=True)
class CleaningStep:
    """A single atomic operation within a CleaningStrategy.

    Attributes:
        operation: Which deterministic operation to apply.
        target_column: Column the operation applies to, or None for
            dataset-wide operations (e.g. EXACT_DEDUPLICATION).
        parameters: Operation-specific parameters (e.g. `{"fill_value": 0}`
            for CONSTANT_IMPUTATION, or `{"iqr_multiplier": 1.5}` for the
            outlier operations). Stored as a plain dict so it serializes
            directly into the SQLite `strategy_definition_json` column
            (Phase 2, Section 7).
    """

    operation: CleaningOperation
    target_column: str | None = None
    parameters: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict (for persistence, Phase 4 repos)."""
        return {
            "operation": self.operation.value,
            "target_column": self.target_column,
            "parameters": dict(self.parameters),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CleaningStep:
        return cls(
            operation=CleaningOperation(data["operation"]),
            target_column=data.get("target_column"),
            parameters=dict(data.get("parameters", {})),
        )


@dataclass(frozen=True)
class CleaningStrategy:
    """An ordered sequence of CleaningSteps representing one candidate strategy.

    Attributes:
        strategy_id: Stable UUID, generated by the Domain layer (not the
            database) so the same ID is usable across WorkflowState, SQLite
            rows, and exported filenames (Phase 2, Section 7 design decision).
        name: Short, human-readable name (e.g. "Median Imputation + IQR Clipping").
        steps: Ordered tuple of CleaningStep. Order matters: steps are applied
            sequentially (e.g. dtype coercion before outlier detection, since
            outlier detection on a numeric column requires numeric dtype).
        is_baseline: True for the low-cost "minimal intervention" strategy
            (analogous in spirit to the paper's low-cost baseline assignment
            before the greedy-upgrade pass, Phase 1 Appendix A) 🟦-motivated.
        description: Human-readable summary of what this strategy does and
            why it was generated, used as grounding for Phase 7's explanation
            (not written by an LLM at generation time).
    """

    strategy_id: str
    name: str
    steps: tuple[CleaningStep, ...]
    is_baseline: bool = False
    description: str = ""

    def __post_init__(self) -> None:
        if not self.strategy_id:
            raise ValueError("strategy_id must not be empty")
        if not self.name:
            raise ValueError("CleaningStrategy.name must not be empty")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-compatible dict for the `strategy_definition_json` column."""
        return {
            "strategy_id": self.strategy_id,
            "name": self.name,
            "steps": [step.to_dict() for step in self.steps],
            "is_baseline": self.is_baseline,
            "description": self.description,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> CleaningStrategy:
        return cls(
            strategy_id=data["strategy_id"],
            name=data["name"],
            steps=tuple(CleaningStep.from_dict(step) for step in data["steps"]),
            is_baseline=data.get("is_baseline", False),
            description=data.get("description", ""),
        )
