"""Domain entity representing a single detected data-quality issue.

The four issue types below correspond directly to Phase 1's Functional
Requirement FR-2 ("...detect missing values, duplicates, outliers, and
inconsistent data types"). Detection logic (which requires Pandas) lives in
`infrastructure/data_processing/issue_detector.py`; this module defines only
the resulting data shape.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class IssueType(str, Enum):
    """The four data-quality issue categories in scope (Phase 1, FR-2)."""

    MISSING_VALUES = "missing_values"
    DUPLICATE_ROWS = "duplicate_rows"
    OUTLIERS = "outliers"
    INCONSISTENT_DTYPE = "inconsistent_dtype"


@dataclass(frozen=True)
class DataIssue:
    """A single, specific data-quality issue detected in a dataset.

    Attributes:
        issue_type: One of the four in-scope issue categories.
        column: The affected column name, or None for dataset-wide issues
            (e.g. duplicate rows span the whole row, not a single column).
        severity: Normalized severity in [0.0, 1.0], where 1.0 means the
            issue affects the entire column/dataset. Used by
            `StrategyGenerator` (Phase 4) to decide which strategies are
            worth generating, and later by the Evaluation Agent (Phase 6)
            as an input to the data_quality_score objective.
        affected_row_count: Absolute number of rows affected by this issue.
        description: Human-readable explanation, surfaced verbatim in the
            Streamlit dashboard (Phase 9) and available to the Decision &
            Reporting Agent's explanation prompt (Phase 7) as grounding
            evidence -- not generated by an LLM.
    """

    issue_type: IssueType
    column: str | None
    severity: float
    affected_row_count: int
    description: str

    def __post_init__(self) -> None:
        if not (0.0 <= self.severity <= 1.0):
            raise ValueError(f"severity must be within [0.0, 1.0], got {self.severity}")
        if self.affected_row_count < 0:
            raise ValueError("affected_row_count cannot be negative")
        if self.issue_type != IssueType.DUPLICATE_ROWS and self.column is None:
            raise ValueError(
                f"column is required for issue_type={self.issue_type.value} "
                "(only DUPLICATE_ROWS is dataset-wide)"
            )
